approach_planner:
  planning_groups: # Sorted by order of preference
    - left_arm
    - right_arm
    - torso
    - both_arms_torso

  exclude_from_planning_joints:
    - head_1_joint
    - head_2_joint
    - gripper_right_joint
    - gripper_left_joint

  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
  skip_planning_approach_min_dur: 0.5
